### ISSUE TITLE
Requesting Attachments of Documents

### ISSUE THREAD

**Issue by Natural-thirsty** [mathiv11/whatsup.Development#5]
Hi Mathi,
       It would be great if the app is capable of attaching  the document as well. Kindly add this feature.

**Comment by mathiv11** [comment]
Hi, Natural, Thanks for suggesting this feature. We will and let you know.

**Comment by mathiv11** [comment]
Hi, Natural thanks for your valuabe suggestions.  This feature is going to make our product great
